title: PGroonga
markdown: kramdown
highlighter: rouge
pgroonga_version: 2.2.8
pgroonga_release_date: 2020-12-27
postgresql_doc_base_url:
  en: https://www.postgresql.org/docs/13
  ja: https://www.postgresql.jp/document/13/html
windows_postgresql_versions:
  - 9.6
  - 10
  - 11
  - 12
  - 13
latest_postgresql_version: 13
freebsd_postgresql_version: 13
amazon_linux_postgresql_version:
  major: 10
  package: 10.9-1PGDG
development_postgresql_version: 14.0
exclude:
  - "Rakefile"
  - "Gemfile"
  - "Gemfile.lock"
  - "data"
  - "vendor"
description:
  en: Make PostgreSQL fast full text search platform for all languages!
  ja: PostgreSQLで高速日本語全文検索！

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
  sass_dir: assets/stylesheets

defaults:
  - scope:
      path: "ja"
    values:
      path_prefix: /ja/
      layout: "base"
      language: ja
      country: JP
  - scope:
      path: ""
    values:
      path_prefix: /
      layout: "base"
      language: en
      country: US
